# Video Processing for BT Lab
This notebook to test code fragments
<br>
<br>
![UofC logo](./pictures/uofc_logo-black.jpg)

In [3]:
#import libraries
import os
import cv2
import json
import re
import datetime
import time
import platform
import numpy as np
import pandas as pd
import shutil
import glob
import io
import imghdr
from PIL import Image

C:\Users\chris\AppData\Local\Temp\ipykernel_26956\2773291406.py:14: DeprecationWarning: 'imghdr' is deprecated and slated for removal in Python 3.13
  import imghdr


In [14]:
import os
import cv2

def is_png_corrupted(file_path):
    try:
        image = cv2.imread(file_path, cv2.IMREAD_UNCHANGED)
        if image is None:
            return True
        return False
    except Exception:
        return True

def check_for_corrupted_png_files(folder_path):
    corrupted_files = []
    for root, _, files in os.walk(folder_path):
        for file in files:
            if file.lower().endswith(".png"):
                file_path = os.path.join(root, file)
                if is_png_corrupted(file_path):
                    corrupted_files.append(file_path)

    return corrupted_files

if __name__ == "__main__":
    folder_path = 'C:/Christian/DI_centre_structured/DI_CAMERA_P3225/Final/Arun/2 Meters/With Blankets/Hold Breath/frames_Arun2_lower_bound'  # Replace with the actual folder path containing PNG files
    corrupted_files = check_for_corrupted_png_files(folder_path)
    
    if len(corrupted_files) == 0:
        print("No corrupted PNG files found.")
    else:
        print("Corrupted PNG files found:")
        for file_path in corrupted_files:
            print(file_path)

Corrupted PNG files found:
C:/Christian/DI_centre_structured/DI_CAMERA_P3225/Final/Arun/2 Meters/With Blankets/Hold Breath/frames_Arun2_lower_bound\frame_6969.png


In [10]:
png_file = r"C:\Users\chris\Documents\Projects Outside of School\repo\Video-Processing\frame_6969.png"
png_file2 = r"C:\Christian\DI_centre_structured\DI_CAMERA_P3225\Final\Arun\2 Meters\With Blankets\Hold Breath\frames_Arun2_lower_bound\frame_0.png"

image = cv2.imread(png_file2, cv2.IMREAD_UNCHANGED)
print(image)

[[[127 127 127]
  [122 122 122]
  [127 127 127]
  ...
  [122 122 120]
  [135 135 133]
  [142 142 140]]

 [[128 128 128]
  [125 125 125]
  [128 128 128]
  ...
  [121 121 119]
  [123 123 121]
  [125 125 123]]

 [[129 129 129]
  [132 132 132]
  [129 129 129]
  ...
  [123 123 121]
  [121 121 119]
  [120 120 118]]

 ...

 [[128 128 128]
  [129 129 129]
  [123 123 123]
  ...
  [126 126 126]
  [126 126 126]
  [126 126 126]]

 [[136 136 136]
  [129 129 129]
  [123 123 123]
  ...
  [126 126 126]
  [126 126 126]
  [126 126 126]]

 [[140 140 140]
  [129 129 129]
  [123 123 123]
  ...
  [126 126 126]
  [126 126 126]
  [126 126 126]]]


In [12]:
def create_corrupted_png(file_path):
    # Create a random numpy array (this will be treated as an image)
    image = np.random.randint(0, 256, size=(100, 100, 3), dtype=np.uint8)
    
    # Write the numpy array to a PNG file
    cv2.imwrite(file_path, image)
    
    # Now, let's manually corrupt the file by overwriting a part of it
    with open(file_path, "rb+") as file:
        file.seek(10)  # Move to an arbitrary position in the file
        file.write(b"corruption")  # Write some random data to corrupt the file

In [13]:
png_file = "C:/Users/chris/Documents/Projects Outside of School/repo/Video-Processing/frame_0.png"
create_corrupted_png(png_file)